Pc = imread('../images/mrt-train.jpg');
% whos Pc;
P = rgb2gray(Pc);
% whos P;
% imshow(P);
P_minVal = double(min(P(:)));
P_maxVal = double(max(P(:)));
subOperation = imsubtract(P, P_minVal);
P2 = immultiply(subOperation, 255 / (P_maxVal - P_minVal));
imshow(P2);